In [55]:
import torch
from torch.autograd import Variable
from torch import nn 
from torch import optim

### Создайте случайный FloatTensor размера 3x4x5

In [8]:
tensor = torch\
  .rand(3, 4, 5)\
  .type(torch.float32)

print(tensor)

tensor([[[0.9614, 0.0700, 0.8477, 0.8517, 0.1854],
         [0.5971, 0.4860, 0.3074, 0.4125, 0.8558],
         [0.2213, 0.1671, 0.3928, 0.5020, 0.4447],
         [0.1652, 0.3028, 0.6124, 0.9661, 0.8086]],

        [[0.4850, 0.8497, 0.0111, 0.7928, 0.4332],
         [0.6473, 0.6739, 0.6805, 0.2909, 0.7262],
         [0.9558, 0.9745, 0.7477, 0.5478, 0.4009],
         [0.6907, 0.7188, 0.0583, 0.3217, 0.2108]],

        [[0.7610, 0.9117, 0.2444, 0.8031, 0.7450],
         [0.4009, 0.3815, 0.3338, 0.8264, 0.2289],
         [0.3509, 0.0729, 0.0931, 0.2406, 0.4980],
         [0.8054, 0.5493, 0.2508, 0.1734, 0.0119]]])


### Выведите его форму (shape)

In [9]:
tensor.shape

torch.Size([3, 4, 5])

### Приведите его к форме 6 X 10

In [12]:
print(tensor.view(6, 10))

tensor([[0.9614, 0.0700, 0.8477, 0.8517, 0.1854, 0.5971, 0.4860, 0.3074, 0.4125,
         0.8558],
        [0.2213, 0.1671, 0.3928, 0.5020, 0.4447, 0.1652, 0.3028, 0.6124, 0.9661,
         0.8086],
        [0.4850, 0.8497, 0.0111, 0.7928, 0.4332, 0.6473, 0.6739, 0.6805, 0.2909,
         0.7262],
        [0.9558, 0.9745, 0.7477, 0.5478, 0.4009, 0.6907, 0.7188, 0.0583, 0.3217,
         0.2108],
        [0.7610, 0.9117, 0.2444, 0.8031, 0.7450, 0.4009, 0.3815, 0.3338, 0.8264,
         0.2289],
        [0.3509, 0.0729, 0.0931, 0.2406, 0.4980, 0.8054, 0.5493, 0.2508, 0.1734,
         0.0119]])


### Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [13]:
tensor * torch.DoubleTensor([1, 4, 2, 2, 1])

tensor([[[0.9614, 0.2799, 1.6954, 1.7033, 0.1854],
         [0.5971, 1.9439, 0.6149, 0.8250, 0.8558],
         [0.2213, 0.6685, 0.7856, 1.0041, 0.4447],
         [0.1652, 1.2113, 1.2248, 1.9322, 0.8086]],

        [[0.4850, 3.3987, 0.0221, 1.5856, 0.4332],
         [0.6473, 2.6957, 1.3610, 0.5817, 0.7262],
         [0.9558, 3.8981, 1.4955, 1.0955, 0.4009],
         [0.6907, 2.8753, 0.1165, 0.6434, 0.2108]],

        [[0.7610, 3.6470, 0.4888, 1.6062, 0.7450],
         [0.4009, 1.5259, 0.6677, 1.6528, 0.2289],
         [0.3509, 0.2916, 0.1862, 0.4811, 0.4980],
         [0.8054, 2.1971, 0.5016, 0.3467, 0.0119]]], dtype=torch.float64)

### Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [15]:
tensor_6_10 = tensor.view(6, 10)
tensor_6_10_T = torch.transpose(tensor_6_10, 1, 0)

result = torch.matmul(tensor_6_10, tensor_6_10_T)

print(result)

tensor([[3.9972, 2.5920, 2.9553, 3.2546, 2.8890, 1.6252],
        [2.5920, 2.7621, 2.4402, 1.9700, 2.5209, 1.0987],
        [2.9553, 2.4402, 3.7216, 3.1256, 3.2563, 1.7609],
        [3.2546, 1.9700, 3.1256, 4.0283, 3.4219, 1.8315],
        [2.8890, 2.5209, 3.2563, 3.4219, 3.8232, 1.6826],
        [1.6252, 1.0987, 1.7609, 1.8315, 1.6826, 1.4865]])


### Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [19]:
x = Variable(torch.FloatTensor([1]),   requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2]),   requires_grad = True)

y = x**3 + z -75*t

y.backward([x, z, t])

(x.grad, z.grad, t.grad)

(tensor([3.]), tensor([1.]), tensor([-75.]))

### Создайте единичный тензор размера 5x6

In [21]:
ones_tensor = torch.ones((5, 6))

print(ones_tensor)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


### Переведите его в формат numpy

In [23]:
print(ones_tensor.numpy())

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


### Давайте теперь пооптимизируем: возьмите функцию y = x\**w1 - 2 * x\**2 + 5

In [80]:
x = torch.FloatTensor([1])
w1 = Variable(torch.FloatTensor([1]), requires_grad=True)

y = x**w1 - 2*x**2 + 5

In [81]:
crit = nn.MSELoss()
optimizer = optim.SGD([w1], lr=0.001)

In [82]:
w1 = nn.Linear(1, 1, bias=False)

In [83]:
optimizer.zero_grad()
x = torch.FloatTensor([5])

pred = x ** w1(torch.FloatTensor([1])) -2 * x**2 + 5
loss = criterion(pred, y)
print(loss)

tensor(2363.1355, grad_fn=<MseLossBackward>)


In [84]:
loss.backward()
optimizer.step()

In [86]:
print(pred)

tensor([-44.6121], grad_fn=<AddBackward0>)


In [87]:
print(w1)
print(w1.weight.grad)

Linear(in_features=1, out_features=1, bias=False)
tensor([[-60.6988]])
